name: test-build

on:
  pull_request:
    branches:
      - develop
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - id: get-url
        uses: tuftsrt/get-pages-url@v1
      - id: test-build
        uses: tuftsrt/sphinx-to-branch@v1
        with:
          source-branch: ${{ github.head_ref }}
          source-directory: source
          destination-directory: ${{ github.base_ref == 'main' && '.' || 'dev' }}
          build-arguments: "--nitpicky --fail-on-warning"
          dry-run: "true"
          use-expect: "true"
          expect-timeout: 300
          expect-pattern-action: |
            "trying URL" {
              puts stderr "EXPECT: intercepted R package installation attempt"
              exit 1
            }
            timeout {
              puts stderr "EXPECT: build timed out after $EXPECT_TIMEOUT seconds"
              exit 1
            }
        env:
          BASEURL: ${{ steps.get-url.outputs.url }}
